services:
  - type: web
    name: cinerec
    env: python
    buildCommand: pip install -r requirements.txt && python models/train.py && python backend/load_data.py
    startCommand: gunicorn --chdir backend app:create_app()
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0